# Generated by Django 5.2.15 on 2026-07-10 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('paypal', 'PayPal'), ('mpesa', 'M-Pesa (Daraja API)'), ('stripe', 'Stripe'), ('manual', 'Manual / Test')], db_index=True, help_text='Gateway originating the webhook delivery.', max_length=50)),
                ('event_id', models.CharField(blank=True, db_index=True, help_text='Unique event or transmission ID provided by the gateway for deduplication.', max_length=255, null=True)),
                ('event_type', models.CharField(blank=True, default='', help_text='Event type string (e.g., CHECKOUT.ORDER.APPROVED, stkCallback).', max_length=100)),
                ('payload', models.JSONField(default=dict, help_text='Full JSON payload received in the webhook body.')),
                ('headers', models.JSONField(default=dict, help_text='Incoming HTTP headers for cryptographic signature verification audit.')),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('duplicate', 'Duplicate'), ('failed', 'Failed'), ('ignored', 'Ignored')], db_index=True, default='processed', help_text='Processing status of this webhook delivery.', max_length=30)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if webhook verification or processing failed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the webhook was received.')),
            ],
            options={
                'verbose_name': 'payment webhook log',
                'verbose_name_plural': 'payment webhook logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gateway', 'event_id'], name='payments_pa_gateway_b3cbe7_idx'), models.Index(fields=['status', '-created_at'], name='payments_pa_status_8c9273_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(db_index=True, help_text='Unique internal payment transaction identifier (e.g., PAY-20260710-000001).', max_length=100, unique=True)),
                ('gateway', models.CharField(choices=[('paypal', 'PayPal'), ('mpesa', 'M-Pesa (Daraja API)'), ('stripe', 'Stripe'), ('manual', 'Manual / Test')], db_index=True, help_text='Payment provider gateway code.', max_length=50)),
                ('transaction_id', models.CharField(blank=True, db_index=True, default='', help_text='Gateway-specific transaction, capture, or receipt ID (e.g., MpesaReceiptNumber, PayPal Capture ID).', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Exact amount requested or paid in this transaction attempt.', max_digits=12)),
                ('currency', models.CharField(default='USD', help_text='ISO currency code (e.g., USD, KES).', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('authorized', 'Authorized'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', help_text='Current monetary lifecycle status of this payment attempt.', max_length=30)),
                ('provider_response', models.JSONField(blank=True, default=dict, help_text='Raw or structured gateway responses for auditing and troubleshooting.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Gateway-specific metadata (e.g., MerchantRequestID, CheckoutRequestID, phone_number).')),
                ('initiated_at', models.DateTimeField(blank=True, help_text='Timestamp when payment processing was initiated with the gateway.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when payment was confirmed, completed, or failed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the payment attempt record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the payment attempt record was last updated.')),
                ('order', models.ForeignKey(help_text='Order associated with this payment attempt.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='payments_pa_order_i_288dd3_idx'), models.Index(fields=['gateway', 'status'], name='payments_pa_gateway_fb31b8_idx'), models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx')],
            },
        ),
    ]
