# Generated by Django 5.2.15 on 2026-07-11 06:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfillment_status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid — Awaiting Processing'), ('processing', 'Processing'), ('picking', 'Picking in Progress'), ('picked', 'Picked'), ('packing', 'Packing in Progress'), ('packed', 'Packed'), ('ready_for_dispatch', 'Ready for Dispatch'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed_delivery', 'Failed Delivery'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('exchanged', 'Exchanged')], db_index=True, default='pending_payment', help_text='Current operational lifecycle state.', max_length=35, verbose_name='fulfillment status')),
                ('priority', models.IntegerField(choices=[(1, 'Urgent (Expedited / Overnight)'), (2, 'High Priority (2-Day / VIP)'), (3, 'Normal Priority (Standard Ground)'), (4, 'Low Priority')], db_index=True, default=3, help_text='Operational priority determining queue ordering.', verbose_name='priority')),
                ('warehouse', models.CharField(db_index=True, default='Main Facility — Operations Hub #1', help_text='Designated warehouse or fulfillment center handling this order.', max_length=100, verbose_name='assigned warehouse')),
                ('notes', models.TextField(blank=True, default='', help_text='External notes or instructions relevant to shipping and handling.', verbose_name='customer/shipping notes')),
                ('internal_notes', models.TextField(blank=True, default='', help_text='Private operational notes shared among warehouse staff.', verbose_name='internal staff notes')),
                ('picking_started_at', models.DateTimeField(blank=True, null=True, verbose_name='picking started at')),
                ('picking_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='picking completed at')),
                ('packing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='packing started at')),
                ('packing_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='packing completed at')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='dispatched at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_packer', models.ForeignKey(blank=True, help_text='Warehouse associate tasked with packing items.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_fulfillments', to=settings.AUTH_USER_MODEL, verbose_name='assigned packer')),
                ('assigned_picker', models.ForeignKey(blank=True, help_text='Warehouse associate tasked with picking items.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_fulfillments', to=settings.AUTH_USER_MODEL, verbose_name='assigned picker')),
                ('assigned_staff', models.ForeignKey(blank=True, help_text="Primary staff member supervising this order's fulfillment.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fulfillments', to=settings.AUTH_USER_MODEL, verbose_name='assigned fulfillment lead')),
                ('order', models.OneToOneField(help_text='Associated customer order.', on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_order', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'fulfillment order',
                'verbose_name_plural': 'fulfillment orders',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FulfillmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, help_text='Category of action or transition (e.g., STATE_CHANGE, PICKING_COMPLETED).', max_length=50, verbose_name='event type')),
                ('description', models.TextField(help_text='Human-readable details regarding what changed.', verbose_name='description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured JSON context (e.g., old status vs new status, missing SKUs).', verbose_name='event metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillment_events', to=settings.AUTH_USER_MODEL, verbose_name='performed by')),
                ('fulfillment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='fulfillment.fulfillmentorder', verbose_name='fulfillment order')),
            ],
            options={
                'verbose_name': 'fulfillment event',
                'verbose_name_plural': 'fulfillment events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('return', 'Return & Refund'), ('exchange', 'Item Exchange')], db_index=True, default='return', max_length=20, verbose_name='request type')),
                ('status', models.CharField(choices=[('requested', 'Requested — Awaiting Approval'), ('approved', 'Approved — Awaiting Return Shipment'), ('rejected', 'Rejected'), ('inspecting', 'Items Received — Under Inspection'), ('completed', 'Completed — Restocked / Resolved')], db_index=True, default='requested', max_length=30, verbose_name='status')),
                ('reason', models.TextField(help_text='Customer stated rationale for returning or exchanging items.', verbose_name='return/exchange reason')),
                ('customer_notes', models.TextField(blank=True, default='', verbose_name='customer notes')),
                ('staff_notes', models.TextField(blank=True, default='', verbose_name='staff inspection notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('fulfillment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='fulfillment.fulfillmentorder', verbose_name='fulfillment order')),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_returns', to=settings.AUTH_USER_MODEL, verbose_name='inspected by')),
            ],
            options={
                'verbose_name': 'return/exchange request',
                'verbose_name_plural': 'return/exchange requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.CharField(db_index=True, default='FedEx Ground', help_text='Designated logistics carrier (e.g., FedEx, UPS, USPS, DHL).', max_length=100, verbose_name='courier / carrier')),
                ('tracking_number', models.CharField(db_index=True, help_text='Carrier tracking barcode or reference number.', max_length=120, unique=True, verbose_name='tracking number')),
                ('shipping_method', models.CharField(default='Standard Ground', help_text='Service level chosen (e.g., Express Overnight, Ground, 2-Day Air).', max_length=100, verbose_name='shipping method')),
                ('shipment_status', models.CharField(choices=[('preparing', 'Preparing Package'), ('label_created', 'Shipping Label Created'), ('picked_up', 'Picked Up by Courier'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('exception', 'Delivery Exception / Delay'), ('failed', 'Failed / Returned to Sender')], db_index=True, default='preparing', max_length=30, verbose_name='shipment status')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='estimated delivery date')),
                ('actual_delivery', models.DateTimeField(blank=True, null=True, verbose_name='actual delivery date')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual billed shipping cost incurred from carrier.', max_digits=10, verbose_name='actual carrier cost')),
                ('package_length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='length (cm)')),
                ('package_width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='width (cm)')),
                ('package_height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='height (cm)')),
                ('package_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='weight (kg)')),
                ('label_url', models.CharField(blank=True, default='', help_text='Foundation placeholder for generated shipping label PDF/ZPL link.', max_length=500, verbose_name='shipping label URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('fulfillment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='fulfillment.fulfillmentorder', verbose_name='fulfillment order')),
            ],
            options={
                'verbose_name': 'shipment',
                'verbose_name_plural': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FulfillmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='target quantity')),
                ('picked_quantity', models.PositiveIntegerField(default=0, verbose_name='picked quantity')),
                ('missing_quantity', models.PositiveIntegerField(default=0, verbose_name='missing / unlocateable quantity')),
                ('is_picked', models.BooleanField(db_index=True, default=False, verbose_name='is picked')),
                ('is_packed', models.BooleanField(db_index=True, default=False, verbose_name='is packed')),
                ('notes', models.CharField(blank=True, default='', help_text='Notes regarding missing items, substitutions, or packaging requirements.', max_length=255, verbose_name='item notes / discrepancy info')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_items', to='orders.orderitem', verbose_name='order item')),
                ('fulfillment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fulfillment.fulfillmentorder', verbose_name='fulfillment order')),
            ],
            options={
                'verbose_name': 'fulfillment item',
                'verbose_name_plural': 'fulfillment items',
                'ordering': ['order_item__id'],
                'unique_together': {('fulfillment_order', 'order_item')},
            },
        ),
    ]
