# Generated by Django 5.2.15 on 2026-07-08 20:03

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_brand_is_active_alter_category_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique promo code (case-insensitive in validation).', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, default='', help_text='Internal or customer-facing description of the coupon.', max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', help_text='Percentage off (0-100) or fixed amount off ($).', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Numerical discount amount or percentage rate.', max_digits=10)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum cart subtotal required to apply this coupon.', max_digits=10)),
                ('maximum_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum monetary discount allowed (useful for capping percentage discounts).', max_digits=10, null=True)),
                ('active', models.BooleanField(default=True, help_text='Master switch to enable or disable this coupon.')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the coupon becomes valid.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Date and time when the coupon expires (null for no expiration).', null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total number of times this coupon can be applied across the platform.', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Current number of times this coupon has been applied/completed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'discount coupon',
                'verbose_name_plural': 'discount coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Public or internal promotion title (e.g., Summer Luxury Sale).', max_length=150)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed rules or customer-facing description.')),
                ('promotion_type', models.CharField(choices=[('store_wide', 'Store-Wide Sale'), ('category', 'Category Discount'), ('product', 'Product Discount'), ('buy_x_get_y', 'Buy X Get Y (Prepared Architecture)')], default='store_wide', help_text='Strategy type governing how items match this promotion.', max_length=30)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', help_text='Percentage off or fixed monetary reduction per applicable unit.', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Numerical discount value.', max_digits=10)),
                ('active', models.BooleanField(default=True, help_text='Master switch to activate or deactivate this promotion.')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the promotion begins.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Date and time when the promotion ends (null for ongoing).', null=True)),
                ('priority', models.PositiveIntegerField(default=10, help_text='Evaluation priority (higher number evaluated/applied first).')),
                ('rules_config', models.JSONField(blank=True, default=dict, help_text='Flexible JSON schema for advanced rules (e.g., Buy X Get Y thresholds).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Categories eligible for this promotion (if Category Discount).', related_name='promotions', to='products.category')),
                ('products', models.ManyToManyField(blank=True, help_text='Specific products eligible for this promotion (if Product Discount).', related_name='promotions', to='products.product')),
            ],
            options={
                'verbose_name': 'promotion',
                'verbose_name_plural': 'promotions',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
