# Generated by Django 5.2.15 on 2026-07-08 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, default='', help_text='Order ID/number generated at checkout completion.', max_length=100)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Exact monetary discount granted by this coupon on the order.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the coupon redemption was logged.')),
                ('coupon', models.ForeignKey(help_text='Coupon redeemed in this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='pricing.coupon')),
                ('user', models.ForeignKey(blank=True, help_text='Customer account that redeemed the coupon (or None for guest checkout).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'coupon usage log',
                'verbose_name_plural': 'coupon usage logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
