# Generated by Django 5.2.15 on 2026-07-11 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_alerts', models.BooleanField(default=True, help_text='Receive critical operational notifications via email.', verbose_name='email alerts')),
                ('low_stock_alerts', models.BooleanField(default=True, help_text='Receive notifications when inventory falls below reorder thresholds.', verbose_name='low stock alerts')),
                ('new_order_alerts', models.BooleanField(default=True, help_text='Receive real-time notifications for newly placed customer orders.', verbose_name='new order alerts')),
                ('system_notification_alerts', models.BooleanField(default=True, help_text='Display in-app system notifications for failed payments and registrations.', verbose_name='system notification alerts')),
                ('dark_mode', models.BooleanField(default=False, help_text='Enable dark theme across the staff administration dashboard.', verbose_name='dark mode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_preferences', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'staff preference',
                'verbose_name_plural': 'staff preferences',
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable role title (e.g., Store Manager).', max_length=100, unique=True, verbose_name='role name')),
                ('code', models.SlugField(help_text='Unique identifier code used in programmatic checks (e.g., store_manager).', max_length=100, unique=True, verbose_name='role code')),
                ('description', models.TextField(blank=True, default='', help_text="Detailed explanation of the role's responsibilities and scope.", verbose_name='description')),
                ('permissions', models.JSONField(blank=True, default=list, help_text="List of permission strings granted by this role (e.g., ['orders.view_order']).", verbose_name='permissions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('users', models.ManyToManyField(blank=True, help_text='Staff members assigned to this role.', related_name='staff_roles', to=settings.AUTH_USER_MODEL, verbose_name='assigned users')),
            ],
            options={
                'verbose_name': 'staff role',
                'verbose_name_plural': 'staff roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('CREATE', 'Create Object'), ('UPDATE', 'Update Object'), ('DELETE', 'Delete Object'), ('VIEW', 'View Object'), ('EXPORT', 'Export Data'), ('ACTION', 'Custom Action')], db_index=True, help_text='Categorization of the administrative action.', max_length=30, verbose_name='action type')),
                ('model_name', models.CharField(blank=True, db_index=True, default='', help_text='Name of the model being acted upon (e.g., Order, Product).', max_length=100, verbose_name='target model')),
                ('object_id', models.CharField(blank=True, default='', help_text='Primary key or identifier of the affected object.', max_length=100, verbose_name='object ID')),
                ('description', models.TextField(help_text='Human-readable summary of the action and any changes made.', verbose_name='description')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the request originated.', null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, help_text='Client browser and OS details.', max_length=512, null=True, verbose_name='user agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Exact time the action occurred.', verbose_name='timestamp')),
                ('user', models.ForeignKey(blank=True, help_text='Staff member who performed the action (null for system automated tasks).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', '-timestamp'], name='dashboard_a_action_81911a_idx'), models.Index(fields=['user', '-timestamp'], name='dashboard_a_user_id_96898d_idx'), models.Index(fields=['model_name', '-timestamp'], name='dashboard_a_model_n_86a6f5_idx')],
            },
        ),
    ]
