# Generated by Django 5.2.15 on 2026-07-06 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verified_user_email_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Customer phone number for order updates and concierge contact.', max_length=30, verbose_name='phone number')),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture. Max size 2MB.', null=True, upload_to='avatars/%Y/%m/', verbose_name='avatar')),
                ('date_of_birth', models.DateField(blank=True, help_text='Optional date of birth for birthday rewards.', null=True, verbose_name='date of birth')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('it', 'Italian'), ('ar', 'Arabic')], default='en', help_text='Preferred communication language.', max_length=10, verbose_name='preferred language')),
                ('preferred_currency', models.CharField(choices=[('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)'), ('CHF', 'CHF (CHF)')], default='USD', help_text='Preferred display currency.', max_length=3, verbose_name='preferred currency')),
                ('marketing_emails', models.BooleanField(default=True, help_text='Receive exclusive catalog invitations and luxury updates.', verbose_name='marketing emails')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
    ]
