# Generated by Django 5.2.15 on 2026-07-06 20:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Optional date of birth for birthday rewards.', null=True, validators=[accounts.models.validate_not_in_future], verbose_name='date of birth'),
        ),
    ]
