# Generated by Django 5.2.15 on 2026-07-07 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g., Home, Office, Parents', max_length=50, verbose_name='label')),
                ('recipient_name', models.CharField(max_length=150, verbose_name='recipient name')),
                ('phone_number', models.CharField(help_text='Contact phone number for delivery and verification.', max_length=30, verbose_name='phone number')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='company name')),
                ('address_line_1', models.CharField(max_length=255, verbose_name='address line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, verbose_name='address line 2')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('county_or_state', models.CharField(max_length=100, verbose_name='county / state / province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('country', models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('GB', 'United Kingdom'), ('FR', 'France'), ('IT', 'Italy'), ('DE', 'Germany'), ('CH', 'Switzerland'), ('AE', 'United Arab Emirates'), ('SA', 'Saudi Arabia'), ('JP', 'Japan'), ('AU', 'Australia')], default='US', max_length=2, verbose_name='country')),
                ('address_type', models.CharField(choices=[('shipping', 'Shipping Only'), ('billing', 'Billing Only'), ('both', 'Shipping & Billing')], default='both', max_length=10, verbose_name='address type')),
                ('is_default_shipping', models.BooleanField(default=False, verbose_name='default shipping address')),
                ('is_default_billing', models.BooleanField(default=False, verbose_name='default billing address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'ordering': ['-is_default_shipping', '-is_default_billing', '-updated_at'],
            },
        ),
    ]
