# Generated by Django 5.2.15 on 2026-07-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_address'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', '-is_default_shipping', '-is_default_billing'], name='address_user_default_idx'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_shipping', True)), fields=('user',), name='unique_default_shipping_per_user'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_billing', True)), fields=('user',), name='unique_default_billing_per_user'),
        ),
    ]
