# Generated by Django 5.2.15 on 2026-07-07 16:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_address_address_user_default_idx_and_more'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('registration', 'Account Registration'), ('login', 'Successful Login'), ('password_change', 'Password Changed'), ('password_reset', 'Password Reset Requested'), ('password_reset_complete', 'Password Reset Completed'), ('email_verification', 'Email Verified'), ('email_change_request', 'Email Change Requested'), ('email_change', 'Email Address Changed'), ('address_update', 'Address Book Updated'), ('session_revoked', 'Session Revoked'), ('other_sessions_revoked', 'Other Sessions Revoked'), ('account_deactivation', 'Account Deactivated'), ('account_deletion', 'Account Deleted')], db_index=True, max_length=50, verbose_name='event type')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='user agent')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='details')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'account activity log',
                'verbose_name_plural': 'account activity logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PendingEmailChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=254, verbose_name='new email address')),
                ('token', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='verification token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_email_changes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'pending email change',
                'verbose_name_plural': 'pending email changes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='session key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='user agent')),
                ('last_activity', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='last activity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_session', to='sessions.session', verbose_name='django session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user session',
                'verbose_name_plural': 'user sessions',
                'ordering': ['-last_activity'],
            },
        ),
    ]
