# Generated by Django 5.2.15 on 2026-07-08 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(help_text='Full name of the recipient.', max_length=150)),
                ('phone_number', models.CharField(help_text='Contact number for delivery notifications.', max_length=30)),
                ('company_name', models.CharField(blank=True, default='', help_text='Optional company name.', max_length=100)),
                ('address_line_1', models.CharField(help_text='Street address, P.O. box, or business department.', max_length=255)),
                ('address_line_2', models.CharField(blank=True, default='', help_text='Apartment, suite, unit, or building floor.', max_length=255)),
                ('city', models.CharField(help_text='City or municipality.', max_length=100)),
                ('county_or_state', models.CharField(help_text='State, province, or county.', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', help_text='ZIP or postal code.', max_length=20)),
                ('country', models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('GB', 'United Kingdom'), ('FR', 'France'), ('IT', 'Italy'), ('DE', 'Germany'), ('CH', 'Switzerland'), ('AE', 'United Arab Emirates'), ('SA', 'Saudi Arabia'), ('JP', 'Japan'), ('AU', 'Australia')], default='US', help_text='Standardized ISO 2-letter country code.', max_length=2)),
            ],
            options={
                'verbose_name': 'checkout address',
                'verbose_name_plural': 'checkout addresses',
            },
        ),
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Django session key for anonymous guest checkouts.', max_length=40, null=True)),
                ('billing_same_as_shipping', models.BooleanField(default=True, help_text='Indicates whether the billing address is identical to shipping.')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional customer checkout or delivery notes.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', help_text='Current state of checkout session progression.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Timestamp when the checkout session is flagged as invalid/expired.')),
                ('billing_address', models.ForeignKey(blank=True, help_text='Snapshotted billing address.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_sessions', to='checkout.checkoutaddress')),
                ('cart', models.OneToOneField(help_text='Shopping cart associated with this checkout flow.', on_delete=django.db.models.deletion.CASCADE, related_name='checkout_session', to='cart.cart')),
                ('shipping_address', models.ForeignKey(blank=True, help_text='Snapshotted shipping address.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_sessions', to='checkout.checkoutaddress')),
                ('user', models.ForeignKey(blank=True, help_text='Optional customer account associated with this session.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'checkout session',
                'verbose_name_plural': 'checkout sessions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
