# Generated by Django 5.2.15 on 2026-07-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='House of Bore', help_text='Public display name shown on storefront navigation and browser tabs.', max_length=150, verbose_name='Store Name')),
                ('business_name', models.CharField(default='House of Bore Luxury Ltd.', help_text='Official corporate entity name used in invoices and legal documents.', max_length=255, verbose_name='Legal Business Name')),
                ('store_description', models.TextField(default='Premium luxury garments and bespoke fashion tailored for timeless silhouettes.', help_text='Brief overview of the store shown in footers and default metadata.', verbose_name='Store Description')),
                ('logo', models.ImageField(blank=True, help_text='Primary logo image (PNG or SVG recommended).', null=True, upload_to='branding/logos/', verbose_name='Store Logo')),
                ('favicon', models.ImageField(blank=True, help_text='Small icon displayed in browser tabs (ICO or PNG 32x32).', null=True, upload_to='branding/favicons/', verbose_name='Store Favicon')),
                ('email', models.EmailField(default='concierge@houseofbore.com', help_text='Public contact email shown on contact page and customer inquiries.', max_length=254, verbose_name='General Contact Email')),
                ('phone', models.CharField(default='+254 700 000 000', help_text='Contact telephone number with country code.', max_length=50, verbose_name='Primary Telephone')),
                ('whatsapp', models.CharField(default='+254 700 000 000', help_text='WhatsApp contact number for instant concierge messaging.', max_length=50, verbose_name='WhatsApp Business Number')),
                ('physical_address', models.TextField(default='Bore House, 4th Floor, Kimathi Street, Nairobi, Kenya', help_text='Store or headquarters address displayed on invoices and contact page.', verbose_name='Physical Address')),
                ('business_hours', models.CharField(default='Mon - Sat: 9:00 AM - 6:00 PM EAT', help_text='Publicly displayed operating schedule.', max_length=255, verbose_name='Business Operating Hours')),
                ('primary_color', models.CharField(default='#1A1A1A', help_text='Primary color code for headers, footers, and major UI elements (e.g., #1A1A1A).', max_length=20, verbose_name='Primary Brand Color (Hex)')),
                ('secondary_color', models.CharField(default='#4A4A4A', help_text='Secondary neutral color code for text and borders (e.g., #4A4A4A).', max_length=20, verbose_name='Secondary Color (Hex)')),
                ('accent_color', models.CharField(default='#C5A059', help_text='Highlight color code for buttons, badges, and accents (e.g., #C5A059).', max_length=20, verbose_name='Accent / Gold Color (Hex)')),
                ('footer_text', models.TextField(default='Crafted with intention, delivered with care. Exploring the intersection of heritage couture and modern comfort.', help_text='Descriptive text displayed in the footer brand column.', verbose_name='Footer Tagline Text')),
                ('announcement_banner_enabled', models.BooleanField(default=True, help_text='Display a top-of-page announcement bar across the storefront.', verbose_name='Enable Announcement Banner')),
                ('announcement_banner_text', models.CharField(default='Complimentary concierge delivery across East Africa on orders above KSh 50,000.', help_text='Promotional or informational text inside the top banner.', max_length=255, verbose_name='Announcement Banner Text')),
                ('default_placeholder_image', models.ImageField(blank=True, help_text='Fallback image shown when products or variants lack uploaded media.', null=True, upload_to='branding/placeholders/', verbose_name='Default Placeholder Image')),
                ('default_currency', models.CharField(default='KES', help_text='ISO currency code (e.g., KES, USD, EUR, GBP).', max_length=10, verbose_name='Default Currency Code')),
                ('currency_symbol', models.CharField(default='KSh', help_text='Symbol prepended to prices across the store (e.g., KSh, $, €).', max_length=10, verbose_name='Currency Symbol')),
                ('decimal_precision', models.PositiveSmallIntegerField(default=2, help_text='Number of decimal digits shown on prices (typically 2, or 0 for whole currency units).', verbose_name='Decimal Precision')),
                ('tax_enabled', models.BooleanField(default=True, help_text='Whether value added tax (VAT/GST) is calculated on orders.', verbose_name='Enable Tax Calculations')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=16.0, help_text='Standard tax rate applied to taxable items (e.g., 16.00 for 16% VAT).', max_digits=5, verbose_name='Tax Rate Percentage')),
                ('tax_display_mode', models.CharField(choices=[('inclusive', 'Inclusive of Tax (Prices displayed already include tax)'), ('exclusive', 'Exclusive of Tax (Tax added at checkout)')], default='inclusive', help_text='Determine whether storefront product prices are shown inclusive or exclusive of tax.', max_length=20, verbose_name='Tax Display Mode')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=50000.0, help_text='Cart subtotal required for customer to qualify for free shipping.', max_digits=12, verbose_name='Free Shipping Order Threshold')),
                ('flat_shipping_rate', models.DecimalField(decimal_places=2, default=1500.0, help_text='Default shipping cost applied when order is below free shipping threshold.', max_digits=12, verbose_name='Standard Flat Shipping Rate')),
                ('local_pickup_enabled', models.BooleanField(default=True, help_text='Allow customers to choose complimentary local pickup during checkout.', verbose_name='Enable Local Studio Pickup')),
                ('estimated_delivery_message', models.CharField(default='Standard Delivery: 2-4 Business Days', help_text='Public timeframe shown on product pages and checkout options.', max_length=150, verbose_name='Estimated Delivery Timeframe')),
                ('default_shipping_policy', models.TextField(default='Orders dispatched within 24 hours via insured courier service with signature confirmation upon arrival.', help_text='Concise shipping summary displayed in shipping drawers and cart.', verbose_name='Short Shipping Policy Summary')),
                ('store_sender_name', models.CharField(default='House of Bore Concierge', help_text='Name displayed as the sender on automated order and account emails.', max_length=150, verbose_name='Store Sender Name')),
                ('reply_to_email', models.EmailField(default='support@houseofbore.com', help_text='Address where customer replies to automated notifications are directed.', max_length=254, verbose_name='Reply-To Email Address')),
                ('customer_support_email', models.EmailField(default='support@houseofbore.com', help_text='Dedicated customer support inbox address.', max_length=254, verbose_name='Customer Support Email')),
                ('order_notification_recipients', models.TextField(default='orders@houseofbore.com', help_text='Comma-separated list of staff email addresses that receive alert notifications when new orders are placed.', verbose_name='Order Notification Recipients')),
                ('default_meta_title', models.CharField(default='House of Bore | Luxury Garments & Bespoke Fashion', help_text='Default title tag when a specific product or page title is not set.', max_length=200, verbose_name='Default Meta Title')),
                ('default_meta_description', models.TextField(default="Explore House of Bore's exquisite collection of luxury garments, tailored silhouettes, and timeless couture.", help_text='Default meta description used by search engines and social cards.', verbose_name='Default Meta Description')),
                ('default_og_image', models.ImageField(blank=True, help_text='Image displayed when pages are shared on social media (1200x630 recommended).', null=True, upload_to='branding/seo/', verbose_name='Default Open Graph Share Image')),
                ('default_social_share_description', models.TextField(default='Discover luxury fashion and timeless elegance at House of Bore.', help_text='Brief description snippet used for social graph sharing cards.', verbose_name='Default Social Share Description')),
                ('robots_index_preference', models.CharField(choices=[('index, follow', 'Index, Follow (Recommended for Production Storefront)'), ('noindex, nofollow', 'NoIndex, NoFollow (Recommended for Staging / Private)'), ('index, nofollow', 'Index, NoFollow')], default='index, follow', help_text='Instructs web crawlers and search engines whether to index the site.', max_length=50, verbose_name='Robots Indexing Preference')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/houseofbore', help_text='Full URL to Facebook page.', verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/houseofbore', help_text='Full URL to Instagram profile.', verbose_name='Instagram URL')),
                ('twitter_url', models.URLField(blank=True, default='https://x.com/houseofbore', help_text='Full URL to X / Twitter profile.', verbose_name='X (Twitter) URL')),
                ('tiktok_url', models.URLField(blank=True, default='https://tiktok.com/@houseofbore', help_text='Full URL to TikTok profile.', verbose_name='TikTok URL')),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com/@houseofbore', help_text='Full URL to YouTube channel.', verbose_name='YouTube Channel URL')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/company/houseofbore', help_text='Full URL to LinkedIn company page.', verbose_name='LinkedIn Company URL')),
                ('maintenance_mode_enabled', models.BooleanField(default=False, help_text='If active, public visitors will see a branded maintenance page (503 status). Staff members can still access all pages normally.', verbose_name='Enable Public Maintenance Mode')),
                ('maintenance_message', models.TextField(default='Our digital flagship is undergoing seasonal curation and upgrades. We will return shortly.', help_text='Custom message displayed to visitors on the maintenance screen.', verbose_name='Maintenance Page Message')),
                ('maintenance_return_date', models.DateTimeField(blank=True, help_text='Optional date and time when the store is scheduled to reopen.', null=True, verbose_name='Expected Return Date & Time')),
                ('feature_wishlist', models.BooleanField(default=True, help_text='Allow customers to save products to their personal wishlists.', verbose_name='Wishlist Feature')),
                ('feature_reviews', models.BooleanField(default=True, help_text='Allow customers to submit and view ratings and reviews on product pages.', verbose_name='Product Reviews & Ratings')),
                ('feature_compare', models.BooleanField(default=True, help_text='Enable the floating comparison drawer and side-by-side spec comparison.', verbose_name='Product Comparison Tool')),
                ('feature_recently_viewed', models.BooleanField(default=True, help_text='Track and display recently viewed product history to visitors.', verbose_name='Recently Viewed Products')),
                ('feature_promotions', models.BooleanField(default=True, help_text='Enable coupon code redemption and promotional discount calculations.', verbose_name='Promotions & Discount Engine')),
                ('feature_guest_checkout', models.BooleanField(default=True, help_text='Allow visitors to complete orders without registering for a customer account.', verbose_name='Guest Checkout')),
                ('privacy_policy', models.TextField(default='### Privacy Policy\n\nHouse of Bore treats patron data with the utmost discretion. We collect and process personal details strictly for order fulfillment, personalized concierge services, and secure authentication.', help_text='Full legal text for the Privacy Policy (Supports Markdown formatting).', verbose_name='Privacy Policy Content')),
                ('terms_and_conditions', models.TextField(default='### Terms & Conditions\n\nBy accessing or purchasing from House of Bore, you agree to our terms of service regarding luxury bespoke tailoring, intellectual property rights, and payment verification.', help_text='Full legal text for Terms & Conditions (Supports Markdown formatting).', verbose_name='Terms & Conditions Content')),
                ('shipping_policy', models.TextField(default='### Shipping Policy\n\nAll deliveries are fully insured from our Nairobi flagship studio to your designated address. Signature verification is mandatory upon receipt of all couture packages.', help_text='Full legal text for Shipping Policy (Supports Markdown formatting).', verbose_name='Full Shipping Policy Content')),
                ('returns_policy', models.TextField(default='### Returns Policy\n\nGarments returned in pristine, unworn condition with original authenticity seals within 14 days of receipt are eligible for exchange or store credit.', help_text='Full legal text for Returns & Exchanges Policy (Supports Markdown formatting).', verbose_name='Returns Policy Content')),
                ('refund_policy', models.TextField(default='### Refund Policy\n\nApproved refunds are processed to the original payment method within 5-7 business days after technical inspection of returned garments.', help_text='Full legal text for Refund Policy (Supports Markdown formatting).', verbose_name='Refund Policy Content')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
                'permissions': [('manage_branding', 'Can manage store branding & theme colors'), ('manage_policies', 'Can edit legal store policies'), ('toggle_maintenance', 'Can enable or disable public maintenance mode'), ('manage_featureflags', 'Can toggle store feature flags')],
            },
        ),
    ]
