# Generated by Django 5.2.15 on 2026-07-10 18:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_recentlyviewedproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.PositiveIntegerField(default=0, help_text='Current sellable stock available to customers.')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, help_text='Quantity reserved for pending orders.')),
                ('damaged_quantity', models.PositiveIntegerField(default=0, help_text='Quantity currently marked as damaged or unusable.')),
                ('reorder_level', models.PositiveIntegerField(default=0, help_text='Threshold below which reorder attention is required.')),
                ('reorder_quantity', models.PositiveIntegerField(default=0, help_text='Suggested replenishment quantity.')),
                ('last_stock_check', models.DateTimeField(blank=True, help_text='Most recent stock count or audit timestamp.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_variant', models.OneToOneField(help_text='Associated variant whose stock this record controls.', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'inventory',
                'verbose_name_plural': 'inventory',
                'ordering': ['product_variant__product__name', 'product_variant__sku'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('initial_stock', 'Initial Stock'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('reservation', 'Reservation'), ('reservation_released', 'Reservation Released'), ('return', 'Return'), ('refund_restock', 'Refund Restock'), ('damage', 'Damage'), ('manual_increase', 'Manual Increase'), ('manual_decrease', 'Manual Decrease'), ('inventory_correction', 'Inventory Correction')], max_length=40)),
                ('quantity', models.IntegerField(help_text='Signed delta applied to stock.')),
                ('previous_quantity', models.IntegerField(help_text='Inventory level before the change.')),
                ('new_quantity', models.IntegerField(help_text='Inventory level after the change.')),
                ('reference_type', models.CharField(blank=True, default='', max_length=50)),
                ('reference_id', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventory')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inventory movement',
                'verbose_name_plural': 'inventory movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['available_quantity', 'reserved_quantity'], name='inventory_i_availab_d89c60_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['reorder_level', 'available_quantity'], name='inventory_i_reorder_bec88e_idx'),
        ),
    ]
