# Generated by Django 5.2.15 on 2026-07-11 08:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInteractionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('phone', 'Phone Call'), ('email', 'Email Correspondence'), ('in_person', 'In-Person Salon Consultation'), ('support_ticket', 'Support Ticket Inquiry')], db_index=True, max_length=50, verbose_name='interaction type')),
                ('summary', models.CharField(max_length=255, verbose_name='summary headline')),
                ('details', models.TextField(blank=True, verbose_name='detailed summary')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_records', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_interactions', to=settings.AUTH_USER_MODEL, verbose_name='performed by')),
            ],
            options={
                'verbose_name': 'customer interaction record',
                'verbose_name_plural': 'customer interaction records',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CustomerStaffNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Private administrative observation or VIP preference note.', verbose_name='note text')),
                ('category', models.CharField(choices=[('general', 'General Inquiry'), ('vip', 'VIP & Concierge Preferences'), ('support', 'Customer Support'), ('order_issue', 'Order / Shipping Escalation'), ('billing', 'Billing & Financial Ledger')], db_index=True, default='general', max_length=50, verbose_name='category')),
                ('is_pinned', models.BooleanField(default=False, help_text='Keep this note pinned to the top of the customer overview card.', verbose_name='pinned to top')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_staff_notes', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_notes', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
            options={
                'verbose_name': 'customer staff note',
                'verbose_name_plural': 'customer staff notes',
                'ordering': ['-is_pinned', '-created_at'],
                'permissions': [('view_customer', 'Can view customer profiles'), ('change_customer', 'Can modify customer profiles and preferences'), ('add_staffnote', 'Can add private staff notes'), ('view_analytics', 'Can view CRM analytics'), ('export_customerdata', 'Can export customer profile and order history data')],
            },
        ),
    ]
