"""
config/settings/base.py
──────────────────────────────────────────────────────────────────────────────
WHY THIS FILE EXISTS:
    Contains every setting that is identical across development, staging, and
    production. Environment-specific files (development.py / production.py)
    import from here and only override what differs.

    Keeping shared settings here prevents duplication and ensures a single
    source of truth for app registration, middleware, templates, etc.
──────────────────────────────────────────────────────────────────────────────
"""

from pathlib import Path

from decouple import Csv, config

# ─── Paths ─────────────────────────────────────────────────────────────────────
# Resolve the project root (two levels above this file: settings/ → config/ → root)
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# ─── Security ──────────────────────────────────────────────────────────────────
# SECRET_KEY is read exclusively from the environment — never hardcoded.
SECRET_KEY = config("SECRET_KEY")


# ─── Application Definition ────────────────────────────────────────────────────
# Split into three groups for readability and to make it easy to identify
# which apps are first-party vs third-party vs Django built-ins.

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS = [
    # django-tailwind: integrates Tailwind CSS build pipeline into Django.
    # Must appear before 'theme' in INSTALLED_APPS.
    "tailwind",
    # The Tailwind theme app generated by `python manage.py tailwind init`.
    # Contains tailwind.config.js, package.json, and the compiled CSS output.
    "theme",
]

LOCAL_APPS = [
    "accounts",      # Custom user model, authentication, profiles
    "core",          # Home page, static pages (about, contact)
    "products",      # Product catalogue, categories, variants
    "cart",          # Shopping cart (session-based)
    "checkout",      # Checkout progress and session management
    "pricing",       # Centralized pricing engine, promotions, coupons
    "orders",        # Order management and history
    "payments",      # Payment gateway integration
    "reviews",       # Product reviews and ratings
    "wishlist",      # User product wishlists
    "dashboard",     # Staff/seller or customer account dashboard
    "notifications", # Centralized, event-driven transactional communications
    "inventory",     # Inventory management, ledger, and stock controls
    "fulfillment",   # Order fulfillment, picking, packing, shipping, and returns workflow
    "crm",           # Customer Relationship Management (CRM) 360° profile & timeline
    "settings",      # Store configuration, branding, policies & feature flags
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS


# ─── Middleware ─────────────────────────────────────────────────────────────────
# Order matters — security and session middleware must come first.
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise (static files) is inserted here in production.py (index 1).
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    # Protects against clickjacking by setting the X-Frame-Options header.
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Enforces configurable zero-downtime maintenance mode for public storefront visitors.
    "settings.middleware.MaintenanceModeMiddleware",
]

ROOT_URLCONF = "config.urls"


# ─── Templates ─────────────────────────────────────────────────────────────────
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Include the project-level templates/ directory so base.html and
        # shared components are resolved before app-level templates.
        "DIRS": [BASE_DIR / "templates"],
        # Also allow each app to have its own templates/<app_name>/ folder.
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                # Exposes the current HttpRequest object to all templates.
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                # Makes the authenticated User object available in templates.
                "django.contrib.auth.context_processors.auth",
                # Makes Django messages (flash alerts) available in templates.
                "django.contrib.messages.context_processors.messages",
                "wishlist.context_processors.wishlist_status",
                "cart.context_processors.cart",
                "settings.context_processors.store_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# ─── Authentication ─────────────────────────────────────────────────────────────
# AUTH_USER_MODEL tells Django to use our custom User model instead of the
# default django.contrib.auth.User.
#
# ✅ PHASE 1.2: Custom User model created in accounts/models.py.
#    This is set before any migration is applied — see accounts/models.py
#    for a full explanation of why changing AUTH_USER_MODEL later is so difficult.
#
AUTH_USER_MODEL = "accounts.User"

# Where to redirect unauthenticated users who try to access a protected view.
LOGIN_URL = "/login/"

# Where to redirect users after a successful login (if no 'next' param present).
LOGIN_REDIRECT_URL = "/"

# Where to redirect users after they log out.
LOGOUT_REDIRECT_URL = "/"

# Authentication backends supporting case-insensitive email login and default ModelBackend
AUTHENTICATION_BACKENDS = [
    "accounts.backends.EmailAuthenticationBackend",
    "django.contrib.auth.backends.ModelBackend",
]


# ─── Password Validation ────────────────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {
        # Rejects passwords that are too similar to the user's personal info.
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        # Enforces a minimum password length (default: 8 characters).
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        # Rejects commonly used passwords (checked against a built-in list).
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        # Rejects passwords that are entirely numeric.
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ─── Internationalization ────────────────────────────────────────────────────────
LANGUAGE_CODE = "en-us"

# East Africa Time — adjust to your deployment region if needed.
# Full list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
TIME_ZONE = "Africa/Nairobi"

# Enable Django's translation framework (required for i18n middleware).
USE_I18N = True

# Store all datetimes as UTC in the database; convert to TIME_ZONE for display.
# This is the safest approach for production systems handling multiple timezones.
USE_TZ = True


# ─── Static Files ───────────────────────────────────────────────────────────────
# URL prefix for static files served in development.
STATIC_URL = "/static/"

# Additional directories where Django will look for static files.
# The project-level static/ folder holds global CSS, JS, images, and fonts.
STATICFILES_DIRS = [BASE_DIR / "static"]

# The directory where 'collectstatic' gathers all static files for deployment.
# This folder should be served by WhiteNoise (production) or a web server.
STATIC_ROOT = BASE_DIR / "staticfiles"


# ─── Media Files ────────────────────────────────────────────────────────────────
# URL prefix for user-uploaded files (product images, avatars, etc.).
MEDIA_URL = "/media/"

# Filesystem path where uploaded files are saved.
# This directory must be writable by the web server process.
MEDIA_ROOT = BASE_DIR / "media"


# ─── Default Primary Key ────────────────────────────────────────────────────────
# Use BigAutoField (64-bit integer) for all auto-generated primary keys.
# More future-proof than the default 32-bit AutoField for large tables.
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ─── Tailwind CSS ───────────────────────────────────────────────────────────────
# Tells django-tailwind which app holds the Tailwind configuration.
# This app is created by `python manage.py tailwind init`.
TAILWIND_APP_NAME = "theme"

# On Windows, Python cannot always locate 'npm' through the system PATH because
# npm is registered as 'npm.cmd' (a batch wrapper). Specifying the full path to
# npm.cmd ensures `manage.py tailwind install` and `tailwind build` work reliably.
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"


# ─── Security Headers (applied in all environments) ────────────────────────────

# Prevents the page from being embedded in a <frame>, <iframe>, or <object>.
# DENY is stricter than SAMEORIGIN and appropriate for e-commerce checkouts.
X_FRAME_OPTIONS = "DENY"

# Sets the X-Content-Type-Options: nosniff header.
# Prevents browsers from guessing (sniffing) the MIME type, which can lead
# to security vulnerabilities when serving user-uploaded content.
SECURE_CONTENT_TYPE_NOSNIFF = True


# ─── Notifications & Email Defaults ─────────────────────────────────────────────
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="House of Bore <noreply@houseofbore.com>")


# ─── Celery Configuration ───────────────────────────────────────────────────────
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default="redis://127.0.0.1:6379/0")
# In development and automated tests, execute tasks eagerly without requiring a live Redis daemon
CELERY_TASK_ALWAYS_EAGER = config("CELERY_TASK_ALWAYS_EAGER", default=True, cast=bool)
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

