# Generated by Django 5.2.15 on 2026-07-08 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='Applied discount coupon.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='pricing.coupon'),
        ),
    ]
