# Generated by Django 5.2.15 on 2026-07-09 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_coupon'),
        ('products', '0004_productoption_productoptionvalue_productvariant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, help_text='Selected product variant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product_variant__isnull', False)), fields=('cart', 'product', 'product_variant'), name='unique_cart_product_variant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product_variant__isnull', True)), fields=('cart', 'product'), name='unique_cart_product_no_variant'),
        ),
    ]
