# Generated by Django 5.2.15 on 2026-07-09 19:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0001_initial'),
        ('products', '0005_productvariant_products_pr_product_04fb7d_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, help_text='Unique human-readable order number (e.g., HOB-20260709-000001).', max_length=32, unique=True)),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Browser session key for guest order verification and access.', max_length=40, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current lifecycle stage of the order.', max_length=30)),
                ('payment_status', models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='awaiting_payment', help_text='Current financial transaction state.', max_length=30)),
                ('fulfillment_status', models.CharField(choices=[('unfulfilled', 'Unfulfilled'), ('partial', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled')], db_index=True, default='unfulfilled', help_text='Physical fulfillment state of order lines.', max_length=30)),
                ('shipping_address_snapshot', models.JSONField(default=dict, help_text='Complete JSON snapshot of the shipping address at order time.')),
                ('billing_address_snapshot', models.JSONField(default=dict, help_text='Complete JSON snapshot of the billing address at order time.')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of line items before discounts, shipping, or taxes.', max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total promotional and coupon discounts applied.', max_digits=12)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated shipping cost.', max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated tax amount.', max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final payable total at creation.', max_digits=12)),
                ('currency', models.CharField(default='USD', help_text='ISO currency code (e.g., USD).', max_length=3)),
                ('customer_notes', models.TextField(blank=True, default='', help_text='Special delivery instructions or notes provided by the customer.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the order was placed.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the order was last updated.')),
                ('checkout_session', models.ForeignKey(blank=True, help_text='Originating checkout session for auditability.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='checkout.checkoutsession')),
                ('user', models.ForeignKey(blank=True, help_text='Customer account associated with the order (null for guest orders).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Snapshot of product title at time of purchase.', max_length=255)),
                ('product_slug', models.CharField(blank=True, default='', help_text='Snapshot of product slug for linking.', max_length=255)),
                ('sku', models.CharField(help_text='Snapshot of specific variant or product SKU.', max_length=100)),
                ('variant_description', models.CharField(blank=True, default='', help_text="Snapshot of option combination string (e.g., 'Size: 40R / Color: Navy').", max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity purchased.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Locked price per unit at order creation.', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Total line cost (`quantity * unit_price`).', max_digits=12)),
                ('order', models.ForeignKey(help_text='Parent order.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, help_text='Optional reference to the live Product (nullable to allow product deletion without affecting order history).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_0ae59f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
    ]
