# Generated by Django 5.2.15 on 2026-07-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='KES', help_text='ISO currency code (e.g., KES).', max_length=3),
        ),
    ]
