# Generated by Django 5.2.15 on 2026-07-10 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], db_index=True, default='email', help_text='Communication channel (Email, SMS, or WhatsApp).', max_length=20)),
                ('event', models.CharField(choices=[('order_created', 'Order Created'), ('payment_successful', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('order_processing', 'Order Processing'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('password_reset', 'Password Reset'), ('account_registered', 'Account Registered')], db_index=True, help_text='Business event triggering this notification.', max_length=50)),
                ('recipient', models.CharField(db_index=True, help_text='Target address (Email address or E.164 phone number).', max_length=255)),
                ('subject', models.CharField(blank=True, default='', help_text='Notification subject or heading.', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current dispatch lifecycle state.', max_length=20)),
                ('provider', models.CharField(blank=True, default='email_smtp', help_text='Adapter code used for delivery (e.g. email_smtp, sms_twilio, whatsapp_cloud).', max_length=50)),
                ('error_message', models.TextField(blank=True, default='', help_text='Detailed error text if delivery attempt encountered an exception.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured template parameters or pre-rendered text/html content.')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts executed so far.')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Timestamp when the message was accepted by the external provider.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when notification record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when notification record was last updated.')),
                ('order', models.ForeignKey(blank=True, help_text='Order associated with this notification (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.order')),
                ('payment', models.ForeignKey(blank=True, help_text='Payment record associated with this notification (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='payments.payment')),
                ('user', models.ForeignKey(blank=True, help_text='Customer account associated with this notification (if registered).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(help_text='Channel over which delivery was attempted.', max_length=20)),
                ('provider', models.CharField(help_text='Provider adapter code.', max_length=50)),
                ('recipient', models.CharField(help_text='Recipient address during this attempt.', max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('retry', 'Retry')], db_index=True, default='success', help_text='Outcome of this specific delivery attempt.', max_length=20)),
                ('error_details', models.TextField(blank=True, default='', help_text='Exception stack trace or provider rejection message.')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Retry attempt number when this log was created.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp of this delivery attempt.')),
                ('notification', models.ForeignKey(help_text='Parent notification record being dispatched.', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'notification delivery log',
                'verbose_name_plural': 'notification delivery logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', '-created_at'], name='notificatio_status_37b3f3_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['channel', 'event'], name='notificatio_channel_025df7_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdeliverylog',
            index=models.Index(fields=['status', '-created_at'], name='notificatio_status_c4da04_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdeliverylog',
            index=models.Index(fields=['notification', '-created_at'], name='notificatio_notific_5f7cd9_idx'),
        ),
    ]
