# Generated by Django 5.2.15 on 2026-07-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', help_text='Communication channel (Email, SMS, or WhatsApp).', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('payment_successful', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('order_processing', 'Order Processing'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('password_reset', 'Password Reset'), ('account_registered', 'Account Registered')], help_text='Business event triggering this notification.', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current dispatch lifecycle state.', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationdeliverylog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('retry', 'Retry')], default='success', help_text='Outcome of this specific delivery attempt.', max_length=20),
        ),
    ]
