# Generated by Django 5.2.15 on 2026-07-05 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand or manufacturer name.', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Unique URL identifier for brand showcases.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Editorial brand story or heritage overview.')),
                ('logo', models.ImageField(blank=True, help_text='Brand logo or crest image.', null=True, upload_to='brands/')),
                ('website', models.URLField(blank=True, default='', help_text='Optional official brand website URL.')),
                ('is_featured', models.BooleanField(default=False, help_text='Designates whether this brand is highlighted on the homepage or showcases.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this brand is active and visible in the store.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name of the category (e.g., Men's Collection).", max_length=100)),
                ('slug', models.SlugField(help_text='Unique URL identifier generated from the name.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional editorial description for category header.')),
                ('image', models.ImageField(blank=True, help_text='Optional category promotional banner or thumbnail.', null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this category is visible in the store catalog.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical nesting. Leave blank for root categories.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
