# Generated by Django 5.2.15 on 2026-07-05 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product title (e.g., The Weatherproof Trench Coat).', max_length=200)),
                ('slug', models.SlugField(help_text='Unique URL slug generated from product name.', max_length=220, unique=True)),
                ('short_description', models.CharField(help_text='Concise summary for product cards and previews.', max_length=300)),
                ('description', models.TextField(help_text='Full detailed description of materials, fit, and craftsmanship.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Current selling price.', max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original retail price before discount (optional).', max_digits=10, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Current available inventory units.')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Threshold quantity triggering low stock alerts.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this product is published and visible in the store.')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight on homepage and curated showcases.')),
                ('is_new_arrival', models.BooleanField(default=False, help_text='Highlight in new season arrivals.')),
                ('meta_title', models.CharField(blank=True, default='', help_text='Custom SEO title (defaults to product name if empty).', max_length=150)),
                ('meta_description', models.CharField(blank=True, default='', help_text='Custom SEO description (defaults to short description if empty).', max_length=255)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Total number of times this product page has been viewed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, help_text='Associated brand house or atelier.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(help_text='Primary collection or category.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='High-resolution garment or product image.', upload_to='products/')),
                ('alt_text', models.CharField(blank=True, default='', help_text='Accessible alternative text describing the image.', max_length=150)),
                ('is_primary', models.BooleanField(default=False, help_text='Designates this image as the primary thumbnail across showcases.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Gallery display order (lower numbers appear first).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Associated product.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
