# Generated by Django 5.2.15 on 2026-07-09 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_brand_is_active_alter_category_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal option name (e.g., Color, Size, Material).', max_length=100)),
                ('display_name', models.CharField(help_text='Customer-facing label on product pages (e.g., Color, Size).', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display priority (lower numbers appear first).')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this option group is active and selectable.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product option',
                'verbose_name_plural': 'product options',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Specific option value (e.g., Black, Medium).', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sorting order within the option group.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(help_text='Parent option group.', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.productoption')),
            ],
            options={
                'verbose_name': 'product option value',
                'verbose_name_plural': 'product option values',
                'ordering': ['option__sort_order', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Unique, human-readable Stock Keeping Unit (e.g., HOB-TSHIRT-BLK-L).', max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, help_text='Optional barcode, UPC, or EAN number.', max_length=100, null=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Optional selling price specifically for this variant (overrides product base price).', max_digits=10, null=True)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional original retail price before discount for this variant.', max_digits=10, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional internal wholesale or manufacturing cost.', max_digits=10, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Available inventory units specifically for this variant.')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Threshold quantity triggering low stock alerts.')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Shipping weight in kg or lbs.', max_digits=8, null=True)),
                ('dimensions', models.CharField(blank=True, default='', help_text='Package dimensions (e.g., 20x15x5 cm).', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Optional variant-specific image (falls back to product primary image if empty).', null=True, upload_to='variants/')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this variant is active and purchasable in the store.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Associated parent catalog product.', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'product variant',
                'verbose_name_plural': 'product variants',
                'ordering': ['product__name', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ordering priority for this option within the variant.')),
                ('option_value', models.ForeignKey(help_text='Assigned option value.', on_delete=django.db.models.deletion.RESTRICT, related_name='variant_options', to='products.productoptionvalue')),
                ('variant', models.ForeignKey(help_text='Parent product variant.', on_delete=django.db.models.deletion.CASCADE, related_name='variant_options', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'variant option',
                'verbose_name_plural': 'variant options',
                'ordering': ['sort_order', 'option_value__option__sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='option_values',
            field=models.ManyToManyField(help_text='Associated option values defining this exact combination.', related_name='variants', through='products.ProductVariantOption', to='products.productoptionvalue'),
        ),
        migrations.AddConstraint(
            model_name='productoptionvalue',
            constraint=models.UniqueConstraint(fields=('option', 'value'), name='unique_option_value'),
        ),
        migrations.AddConstraint(
            model_name='productvariantoption',
            constraint=models.UniqueConstraint(fields=('variant', 'option_value'), name='unique_variant_option_value'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_active', 'stock_quantity'], name='products_pr_is_acti_6e947e_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='products_pr_product_66459e_idx'),
        ),
    ]
