# Generated by Django 5.2.15 on 2026-07-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productoption_productoptionvalue_productvariant_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active', 'stock_quantity'], name='products_pr_product_04fb7d_idx'),
        ),
    ]
